'use client'

import { MessageCircle, Repeat2, Heart, Share } from 'lucide-react'

const exampleTweets = [
  {
    id: 1,
    type: 'Motivational',
    tag: '💪',
    content: "Your future self is watching you right now through memories. Make them proud.\n\nThe work you put in today compounds into the life you'll live tomorrow.",
    likes: 1243,
    retweets: 289,
    replies: 156,
    author: 'Echo AI',
    handle: '@echo_ai',
    avatar: 'bg-gradient-to-br from-indigo-500 to-purple-600',
  },
  {
    id: 2,
    type: 'Business Insight',
    tag: '🚀',
    content: "The best entrepreneurs aren't the ones with the most resources.\n\nThey're the ones who are most resourceful.\n\nStart with what you have. Build with what you learn. Scale with who you meet.",
    likes: 2156,
    retweets: 512,
    replies: 203,
    author: 'Echo AI',
    handle: '@echo_ai',
    avatar: 'bg-gradient-to-br from-blue-500 to-cyan-500',
  },
  {
    id: 3,
    type: 'Viral Tweet',
    tag: '🔥',
    content: "Normalize:\n\n• Working in silence\n• Celebrating small wins privately\n• Building without announcing\n• Being happy for others\n\nSuccess isn't a competition—it's a journey.",
    likes: 8921,
    retweets: 1842,
    replies: 423,
    author: 'Echo AI',
    handle: '@echo_ai',
    avatar: 'bg-gradient-to-br from-orange-500 to-red-500',
  },
]

export default function TweetExamplesSection() {
  return (
    <section id="demo" className="py-24 bg-gray-900">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-16">
          <h2 className="text-3xl font-bold text-white sm:text-4xl mb-4">
            AI-Generated Content That Performs
          </h2>
          <p className="text-gray-400 max-w-2xl mx-auto">
            See examples of posts Echo can create for your account
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
          {exampleTweets.map((tweet) => (
            <div
              key={tweet.id}
              className="rounded-2xl border border-gray-800 bg-black p-6 hover:border-gray-700 transition"
            >
              {/* Tweet Header */}
              <div className="flex items-center gap-3 mb-4">
                <div className={`h-10 w-10 rounded-full ${tweet.avatar} flex items-center justify-center`}>
                  <span className="text-white font-bold">E</span>
                </div>
                <div>
                  <p className="text-white font-semibold text-sm">{tweet.author}</p>
                  <p className="text-gray-500 text-xs">{tweet.handle}</p>
                </div>
              </div>

              {/* Tweet Type Badge */}
              <div className="mb-4">
                <span className="inline-flex items-center gap-1.5 rounded-full bg-gray-800 px-3 py-1 text-xs text-gray-300">
                  <span>{tweet.tag}</span>
                  {tweet.type}
                </span>
              </div>

              {/* Tweet Content */}
              <div className="mb-4">
                <p className="text-white text-sm whitespace-pre-line leading-relaxed">
                  {tweet.content}
                </p>
              </div>

              {/* Engagement Stats */}
              <div className="flex items-center gap-6 text-gray-500">
                <div className="flex items-center gap-2">
                  <MessageCircle className="h-4 w-4" />
                  <span className="text-xs">{tweet.replies.toLocaleString()}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Repeat2 className="h-4 w-4" />
                  <span className="text-xs">{tweet.retweets.toLocaleString()}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Heart className="h-4 w-4" />
                  <span className="text-xs">{tweet.likes.toLocaleString()}</span>
                </div>
                <div className="flex items-center gap-2">
                  <Share className="h-4 w-4" />
                </div>
              </div>
            </div>
          ))}
        </div>

        <p className="mt-8 text-center text-xs text-gray-500">
          * Example posts generated by Echo AI
        </p>
      </div>
    </section>
  )
}
